"""Pydantic schemas for request/response validation across the API."""
from typing import List, Optional
from pydantic import BaseModel, Field, HttpUrl


class BotCreateRequest(BaseModel):
    name: str = Field(..., min_length=1, max_length=100)
    welcome_message: str = Field(default="Hi! How can I help you today?", max_length=300)
    primary_color: str = Field(default="#4F46E5")
    system_prompt: Optional[str] = Field(
        default=None,
        description="Custom persona/instructions for this bot. Falls back to a sensible default.",
    )


class BotResponse(BaseModel):
    bot_id: str
    api_key: str
    name: str
    welcome_message: str
    primary_color: str
    embed_snippet: str


class IngestURLRequest(BaseModel):
    bot_id: str
    url: HttpUrl


class ChatRequest(BaseModel):
    bot_id: str
    session_id: str = Field(..., description="Unique per-visitor conversation id, generated by the widget.")
    message: str = Field(..., min_length=1, max_length=4000)


class SourceChunk(BaseModel):
    content: str
    source: str
    score: Optional[float] = None


class ChatResponse(BaseModel):
    success: bool = True
    reply: str
    sources: List[SourceChunk] = []
    session_id: str


class IngestResponse(BaseModel):
    success: bool = True
    bot_id: str
    chunks_added: int
    source: str


class HealthResponse(BaseModel):
    status: str
    environment: str
    llm_provider: str
